//! One-shot v1 → v2 config-dir migration.
//!
//! Before the lua-config + embedded-defaults landings, every config dir
//! contained materialised prompts under `phases/`, agent definitions
//! under `agents/`, a top-level `config.yaml`, and optional
//! `*.local.yaml` overlays. The new binary reads all of those from the
//! embedded set at runtime, so the materialised copies are dead clutter
//! that confuses readers and shadows nothing.
//!
//! This module detects the legacy layout and rewrites the dir to the
//! new shape on first config consumption: translate the merged YAMLs
//! into a Lua source file, stamp `ravel.config.config_version = 2`,
//! then delete the embedded-defaults files and any newly-empty
//! directories. Idempotent — once stamped, the migration becomes a
//! no-op.
//!
//! Crash recovery: writes happen before deletes, so a crash between
//! the two leaves legacy files on disk and the next call still
//! detects work to do (legacy presence drives detection, not the
//! marker stamp).

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde_yaml::Value;

use crate::bail_with;
use crate::cli::error_context::ResultExt;
use crate::cli::ErrorCode;
use crate::config_lua::KNOWN_AGENTS;
use crate::init::embedded_entries_with_prefix;

/// Marker line stamped into the new `config.lua` so a future v2 → v3
/// migration can branch on the version. Detection of v1 itself does
/// not depend on this — legacy-file presence drives detection — but
/// the stamp is the documented sentinel for the v2 layout.
const VERSION_MARKER_LINE: &str = "ravel.config.config_version = 2";

/// Header comment prefixed to a freshly-translated `config.lua`. The
/// stamp line is included inline so a single write produces a
/// self-describing file.
const GENERATED_HEADER: &str = concat!(
    "-- Auto-generated by ravel-lite v1\u{2192}v2 migration.\n",
    "-- The legacy config.yaml / agents/<name>/config.yaml / tokens.yaml\n",
    "-- files have been translated into this Lua surface and removed.\n",
    "-- See `ravel-lite reference config-and-prompts` for the full API.\n",
);

/// Filenames at the global config root that may carry overlay data
/// alongside an embedded-defaults equivalent. Listed explicitly because
/// the embedded set does not register `*.local.yaml` paths.
const SHARED_LOCAL_OVERLAYS: &[&str] = &["config.local.yaml"];

/// Subdirectories under the global config root that historically held
/// only embedded-defaults files. Pruned (deepest-first) once their
/// contents are removed; never deleted recursively, so any user-owned
/// file inside one of these dirs prevents the prune.
const LEGACY_DIRS_DEEPEST_FIRST: &[&str] = &[
    "agents/claude-code",
    "agents/pi/prompts",
    "agents/pi/subagents",
    "agents/pi",
    "agents",
    "phases",
    "fixed-memory",
];

/// Run the migration if the dir shows v1 indicators. Returns `Ok(true)`
/// if any work happened, `Ok(false)` for a no-op.
pub fn migrate_if_needed(config_dir: &Path) -> Result<bool> {
    let plan = plan_migration(config_dir);
    if plan.is_noop() {
        return Ok(false);
    }

    if plan.needs_translate {
        let body = generate_lua_from_legacy(config_dir)?;
        write_atomic(&config_dir.join("config.lua"), &body)
            .context("write migrated config.lua")
            .with_code(ErrorCode::IoError)?;
    } else if plan.needs_marker_stamp {
        append_marker_to_existing_lua(&config_dir.join("config.lua"))
            .context("stamp version marker into existing config.lua")
            .with_code(ErrorCode::IoError)?;
    }

    delete_legacy_files(config_dir, &plan.legacy_files)
        .context("delete legacy materialised files")
        .with_code(ErrorCode::IoError)?;
    prune_legacy_dirs(config_dir)
        .context("prune empty legacy directories")
        .with_code(ErrorCode::IoError)?;

    Ok(true)
}

#[derive(Debug, Default)]
struct MigrationPlan {
    needs_translate: bool,
    needs_marker_stamp: bool,
    legacy_files: Vec<PathBuf>,
}

impl MigrationPlan {
    fn is_noop(&self) -> bool {
        !self.needs_translate && !self.needs_marker_stamp && self.legacy_files.is_empty()
    }
}

fn plan_migration(config_dir: &Path) -> MigrationPlan {
    let legacy_files = collect_legacy_files(config_dir);
    if legacy_files.is_empty() {
        // No legacy clutter — this dir is already v2 (or fresh).
        // Skip every step; the marker is informational, not load-bearing.
        return MigrationPlan::default();
    }

    let lua_path = config_dir.join("config.lua");
    let lua_exists = lua_path.is_file();
    let lua_has_marker =
        lua_exists && file_contains_line(&lua_path, VERSION_MARKER_LINE).unwrap_or(false);

    MigrationPlan {
        needs_translate: !lua_exists,
        needs_marker_stamp: lua_exists && !lua_has_marker,
        legacy_files,
    }
}

fn collect_legacy_files(config_dir: &Path) -> Vec<PathBuf> {
    let mut out: Vec<PathBuf> = Vec::new();

    // Every embedded default that is also present on disk: this is
    // the closed set of paths the v1 materialiser ever wrote.
    for (rel, _) in embedded_entries_with_prefix("") {
        let candidate = config_dir.join(rel);
        if candidate.is_file() {
            out.push(candidate);
        }
    }

    // Overlays: `*.local.yaml` siblings that the deep-merge YAML
    // loader used to honour. Not in the embedded set, so listed
    // explicitly.
    for rel in SHARED_LOCAL_OVERLAYS {
        push_if_file(config_dir.join(rel), &mut out);
    }
    for agent in KNOWN_AGENTS {
        push_if_file(
            config_dir.join(format!("agents/{agent}/config.local.yaml")),
            &mut out,
        );
        push_if_file(
            config_dir.join(format!("agents/{agent}/tokens.local.yaml")),
            &mut out,
        );
    }

    out
}

fn push_if_file(path: PathBuf, out: &mut Vec<PathBuf>) {
    if path.is_file() {
        out.push(path);
    }
}

fn delete_legacy_files(config_dir: &Path, files: &[PathBuf]) -> Result<()> {
    for path in files {
        // Defence in depth: never delete anything outside the config dir.
        if !path.starts_with(config_dir) {
            bail_with!(
                ErrorCode::InvalidInput,
                "refusing to delete {} — outside config dir {}",
                path.display(),
                config_dir.display()
            );
        }
        match fs::remove_file(path) {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => {
                return Err(e)
                    .with_context(|| format!("remove {}", path.display()))
                    .with_code(ErrorCode::IoError);
            }
        }
    }
    Ok(())
}

fn prune_legacy_dirs(config_dir: &Path) -> Result<()> {
    for rel in LEGACY_DIRS_DEEPEST_FIRST {
        let dir = config_dir.join(rel);
        if !dir.is_dir() {
            continue;
        }
        match fs::remove_dir(&dir) {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::DirectoryNotEmpty => {
                // User has put their own files under one of our former
                // dirs. Leave it alone — the migration only cleans up
                // what it owned.
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => {
                return Err(e)
                    .with_context(|| format!("rmdir {}", dir.display()))
                    .with_code(ErrorCode::IoError);
            }
        }
    }
    Ok(())
}

fn write_atomic(path: &Path, body: &str) -> Result<()> {
    let tmp = path.with_extension("lua.tmp");
    fs::write(&tmp, body)
        .with_context(|| format!("write {}", tmp.display()))
        .with_code(ErrorCode::IoError)?;
    fs::rename(&tmp, path)
        .with_context(|| format!("rename {} -> {}", tmp.display(), path.display()))
        .with_code(ErrorCode::IoError)?;
    Ok(())
}

fn append_marker_to_existing_lua(path: &Path) -> Result<()> {
    let mut existing = fs::read_to_string(path)
        .with_context(|| format!("read {}", path.display()))
        .with_code(ErrorCode::IoError)?;
    if !existing.ends_with('\n') {
        existing.push('\n');
    }
    existing.push_str("\n-- Stamped by ravel-lite v1\u{2192}v2 migration; do not remove.\n");
    existing.push_str(VERSION_MARKER_LINE);
    existing.push('\n');
    write_atomic(path, &existing)
}

fn file_contains_line(path: &Path, needle: &str) -> Result<bool> {
    let body = fs::read_to_string(path)
        .with_context(|| format!("read {}", path.display()))
        .with_code(ErrorCode::IoError)?;
    Ok(body.lines().any(|l| l.trim() == needle))
}

// -- Lua generation --------------------------------------------------

fn generate_lua_from_legacy(config_dir: &Path) -> Result<String> {
    let shared = read_merged_yaml(config_dir, "config.yaml", Some("config.local.yaml"))?
        .unwrap_or_else(|| Value::Mapping(Default::default()));

    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str(VERSION_MARKER_LINE);
    out.push('\n');

    // Shared scalars: agent + headroom. Anything else in the merged
    // map is a v1 schema artefact we never honoured at runtime; drop
    // silently per the migration spec.
    if let Some(agent) = shared.get("agent").and_then(Value::as_str) {
        out.push('\n');
        out.push_str(&format!("ravel.set_agent({})\n", lua_quote(agent)));
    }
    if let Some(headroom) = shared.get("headroom").and_then(Value::as_i64) {
        out.push_str(&format!("ravel.set_headroom({headroom})\n"));
    }

    for agent in KNOWN_AGENTS {
        let agent_cfg = read_merged_yaml(
            config_dir,
            &format!("agents/{agent}/config.yaml"),
            Some(&format!("agents/{agent}/config.local.yaml")),
        )?;
        let tokens = read_merged_yaml(
            config_dir,
            &format!("agents/{agent}/tokens.yaml"),
            Some(&format!("agents/{agent}/tokens.local.yaml")),
        )?;
        if agent_cfg.is_none() && tokens.is_none() {
            continue;
        }

        out.push('\n');
        out.push_str(&format!("-- Agent: {agent}\n"));

        if let Some(cfg) = agent_cfg {
            emit_agent_setters(&mut out, agent, &cfg);
        }
        if let Some(tok) = tokens {
            emit_token_setters(&mut out, agent, &tok);
        }
    }

    Ok(out)
}

fn emit_agent_setters(out: &mut String, agent: &str, cfg: &Value) {
    if let Some(models) = cfg.get("models").and_then(Value::as_mapping) {
        let sorted: BTreeMap<&str, &Value> = models
            .iter()
            .filter_map(|(k, v)| k.as_str().map(|s| (s, v)))
            .collect();
        for (phase, model) in sorted {
            if let Some(model_str) = model.as_str() {
                out.push_str(&format!(
                    "ravel.set_model_for({}, {}, {})\n",
                    lua_quote(agent),
                    lua_quote(phase),
                    lua_quote(model_str)
                ));
            }
        }
    }
    if let Some(provider) = cfg.get("provider").and_then(Value::as_str) {
        out.push_str(&format!(
            "ravel.set_provider_for({}, {})\n",
            lua_quote(agent),
            lua_quote(provider)
        ));
    }
}

fn emit_token_setters(out: &mut String, agent: &str, tokens: &Value) {
    let Some(map) = tokens.as_mapping() else { return };
    let sorted: BTreeMap<&str, &Value> = map
        .iter()
        .filter_map(|(k, v)| k.as_str().map(|s| (s, v)))
        .collect();
    for (name, value) in sorted {
        if let Some(value_str) = value.as_str() {
            out.push_str(&format!(
                "ravel.set_token({}, {}, {})\n",
                lua_quote(agent),
                lua_quote(name),
                lua_quote(value_str)
            ));
        }
    }
}

fn read_merged_yaml(
    config_dir: &Path,
    base_rel: &str,
    overlay_rel: Option<&str>,
) -> Result<Option<Value>> {
    let base_path = config_dir.join(base_rel);
    let overlay_path = overlay_rel.map(|r| config_dir.join(r));

    let mut value: Option<Value> = if base_path.is_file() {
        Some(parse_yaml_file(&base_path)?)
    } else {
        None
    };
    if let Some(p) = overlay_path {
        if p.is_file() {
            let overlay = parse_yaml_file(&p)?;
            value = Some(match value {
                Some(mut existing) => {
                    deep_merge_yaml(&mut existing, overlay);
                    existing
                }
                None => overlay,
            });
        }
    }
    Ok(value)
}

fn parse_yaml_file(path: &Path) -> Result<Value> {
    let body = fs::read_to_string(path)
        .with_context(|| format!("read {}", path.display()))
        .with_code(ErrorCode::IoError)?;
    serde_yaml::from_str::<Value>(&body)
        .with_context(|| format!("parse {} as YAML", path.display()))
        .with_code(ErrorCode::InvalidInput)
}

fn deep_merge_yaml(base: &mut Value, overlay: Value) {
    match (base, overlay) {
        (Value::Mapping(b), Value::Mapping(o)) => {
            for (k, v) in o {
                if let Some(existing) = b.get_mut(&k) {
                    deep_merge_yaml(existing, v);
                } else {
                    b.insert(k, v);
                }
            }
        }
        (slot, other) => {
            *slot = other;
        }
    }
}

/// Quote `s` as a single-quoted Lua string literal. Escapes the
/// minimum set required for Lua's lexer: backslash, single quote, and
/// the line-terminator characters. Embedded YAML values in a
/// ravel-lite config are model names, phase names, and token labels —
/// all simple identifiers in practice — but the escape keeps the
/// generator total over arbitrary input.
fn lua_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            other => out.push(other),
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write(dir: &Path, rel: &str, body: &str) {
        let path = dir.join(rel);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(&path, body).unwrap();
    }

    #[test]
    fn empty_dir_is_a_noop() {
        let dir = TempDir::new().unwrap();
        let migrated = migrate_if_needed(dir.path()).unwrap();
        assert!(!migrated, "empty dir is fresh, not v1");
        assert!(!dir.path().join("config.lua").exists());
    }

    #[test]
    fn v2_dir_with_marker_is_a_noop() {
        let dir = TempDir::new().unwrap();
        write(
            dir.path(),
            "config.lua",
            &format!("-- mine\n{VERSION_MARKER_LINE}\n"),
        );

        let migrated = migrate_if_needed(dir.path()).unwrap();
        assert!(!migrated);
        let content = fs::read_to_string(dir.path().join("config.lua")).unwrap();
        assert!(content.starts_with("-- mine\n"));
    }

    #[test]
    fn pristine_v1_dir_translates_yaml_and_deletes_legacy() {
        let dir = TempDir::new().unwrap();
        write(dir.path(), "config.yaml", "agent: pi\nheadroom: 9000\n");
        write(dir.path(), "config.local.yaml", "headroom: 4242\n");
        write(
            dir.path(),
            "agents/claude-code/config.yaml",
            "models:\n  work: claude-opus-4-7\n  reflect: claude-sonnet-4-6\n",
        );
        write(
            dir.path(),
            "agents/claude-code/config.local.yaml",
            "models:\n  work: ''\n",
        );
        write(
            dir.path(),
            "agents/claude-code/tokens.yaml",
            "TOOL_READ: Read\nTOOL_WRITE: Write\n",
        );
        write(dir.path(), "phases/work.md", "stale\n");
        write(dir.path(), "fixed-memory/coding-style.md", "stale\n");

        let migrated = migrate_if_needed(dir.path()).unwrap();
        assert!(migrated);

        // Legacy files are gone.
        assert!(!dir.path().join("config.yaml").exists());
        assert!(!dir.path().join("config.local.yaml").exists());
        assert!(!dir.path().join("agents/claude-code/config.yaml").exists());
        assert!(!dir.path().join("agents/claude-code/config.local.yaml").exists());
        assert!(!dir.path().join("agents/claude-code/tokens.yaml").exists());
        assert!(!dir.path().join("phases/work.md").exists());
        assert!(!dir.path().join("fixed-memory/coding-style.md").exists());

        // Newly-empty dirs are pruned.
        assert!(!dir.path().join("agents/claude-code").exists());
        assert!(!dir.path().join("agents").exists());
        assert!(!dir.path().join("phases").exists());
        assert!(!dir.path().join("fixed-memory").exists());

        // The new lua mirrors the merged YAML.
        let lua = fs::read_to_string(dir.path().join("config.lua")).unwrap();
        assert!(lua.contains(VERSION_MARKER_LINE));
        assert!(lua.contains("ravel.set_agent('pi')"));
        // Local overlay won the deep-merge for headroom.
        assert!(lua.contains("ravel.set_headroom(4242)"));
        // Local overlay won for the work model; reflect inherits base.
        assert!(lua.contains("ravel.set_model_for('claude-code', 'work', '')"));
        assert!(lua.contains("ravel.set_model_for('claude-code', 'reflect', 'claude-sonnet-4-6')"));
        // Tokens are translated.
        assert!(lua.contains("ravel.set_token('claude-code', 'TOOL_READ', 'Read')"));
    }

    #[test]
    fn second_run_on_v2_is_a_noop() {
        let dir = TempDir::new().unwrap();
        write(dir.path(), "config.yaml", "agent: pi\nheadroom: 9000\n");

        assert!(migrate_if_needed(dir.path()).unwrap(), "first run should migrate");
        let lua_after_first = fs::read_to_string(dir.path().join("config.lua")).unwrap();

        // No legacy files left → nothing to do, even though the marker
        // could theoretically prompt re-translation.
        assert!(!migrate_if_needed(dir.path()).unwrap(), "second run should be a no-op");
        let lua_after_second = fs::read_to_string(dir.path().join("config.lua")).unwrap();
        assert_eq!(lua_after_first, lua_after_second);
    }

    #[test]
    fn crash_between_lua_write_and_legacy_delete_recovers_on_next_run() {
        // Simulate the crash scenario: `config.lua` already written
        // with marker, but legacy files are still on disk because the
        // delete step never finished. The next run must complete the
        // cleanup without losing the user's lua content.
        let dir = TempDir::new().unwrap();
        write(
            dir.path(),
            "config.lua",
            &format!("-- carried over\n{VERSION_MARKER_LINE}\nravel.set_agent('pi')\n"),
        );
        write(dir.path(), "config.yaml", "agent: claude-code\n");
        write(dir.path(), "phases/work.md", "stale\n");

        let migrated = migrate_if_needed(dir.path()).unwrap();
        assert!(migrated);

        // Legacy files cleaned up.
        assert!(!dir.path().join("config.yaml").exists());
        assert!(!dir.path().join("phases/work.md").exists());
        assert!(!dir.path().join("phases").exists());

        // User content preserved verbatim — no re-translation, no
        // duplicate marker.
        let lua = fs::read_to_string(dir.path().join("config.lua")).unwrap();
        assert!(lua.contains("-- carried over"));
        assert!(lua.contains("ravel.set_agent('pi')"));
        assert_eq!(lua.matches(VERSION_MARKER_LINE).count(), 1);
    }

    #[test]
    fn existing_lua_without_marker_gets_marker_appended_user_content_preserved() {
        // Post-init weird state: `init` wrote a stub `config.lua`
        // before this migration shipped, and legacy files still sit
        // around. The migration must keep the user's stub intact and
        // just stamp the marker.
        let dir = TempDir::new().unwrap();
        write(
            dir.path(),
            "config.lua",
            "-- user stub\nravel.set_model('work', '')\n",
        );
        write(dir.path(), "config.yaml", "agent: claude-code\n");
        write(dir.path(), "phases/work.md", "stale\n");

        let migrated = migrate_if_needed(dir.path()).unwrap();
        assert!(migrated);

        let lua = fs::read_to_string(dir.path().join("config.lua")).unwrap();
        assert!(lua.contains("-- user stub"));
        assert!(lua.contains("ravel.set_model('work', '')"));
        assert!(lua.contains(VERSION_MARKER_LINE));
        // Legacy YAML was NOT translated (the user's lua already
        // expresses their intent); it was just deleted.
        assert!(!lua.contains("ravel.set_agent('claude-code')"));
        assert!(!dir.path().join("config.yaml").exists());
        assert!(!dir.path().join("phases").exists());
    }

    #[test]
    fn user_owned_file_under_legacy_dir_blocks_prune() {
        // The migration only deletes paths that v1 ever materialised.
        // If a user dropped their own file under `phases/` for some
        // reason, we delete the embedded-defaults file but leave the
        // dir alone.
        let dir = TempDir::new().unwrap();
        write(dir.path(), "config.yaml", "agent: claude-code\n");
        write(dir.path(), "phases/work.md", "stale\n");
        write(dir.path(), "phases/my-notes.md", "user content\n");

        migrate_if_needed(dir.path()).unwrap();

        assert!(!dir.path().join("phases/work.md").exists(), "embedded path removed");
        assert!(
            dir.path().join("phases/my-notes.md").exists(),
            "user file preserved"
        );
        assert!(dir.path().join("phases").is_dir(), "non-empty dir preserved");
    }

    #[test]
    fn lua_quote_escapes_special_characters() {
        assert_eq!(lua_quote("plain"), "'plain'");
        assert_eq!(lua_quote("it's"), "'it\\'s'");
        assert_eq!(lua_quote("a\\b"), "'a\\\\b'");
        assert_eq!(lua_quote("line1\nline2"), "'line1\\nline2'");
    }

    #[test]
    fn deep_merge_yaml_overlays_nested_maps() {
        let mut base: Value =
            serde_yaml::from_str("models:\n  work: a\n  reflect: b\n").unwrap();
        let overlay: Value = serde_yaml::from_str("models:\n  work: ''\n").unwrap();
        deep_merge_yaml(&mut base, overlay);
        let merged = base.get("models").unwrap().as_mapping().unwrap();
        assert_eq!(merged.get("work").unwrap().as_str().unwrap(), "");
        assert_eq!(merged.get("reflect").unwrap().as_str().unwrap(), "b");
    }
}
